In [1]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = kagglehub.dataset_download("rikdifos/credit-card-approval-prediction")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Neeresh\.cache\kagglehub\datasets\rikdifos\credit-card-approval-prediction\versions\3

In [3]:
df = pd.read_csv("C:/Users/Neeresh/OneDrive/Documents/kagglehub/datasets/rikdifos/credit-card-approval-prediction/versions/3/application_record.csv")
df.head(5)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1

In [4]:
df.shape

(438557, 18)

In [5]:
df.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   438557 non-null  int64
 1   CODE_GENDER          438557 non-null  object
 2   FLAG_OWN_CAR         438557 non-null  object
 3   FLAG_OWN_REALTY      438557 non-null  object
 4   CNT_CHILDREN         438557 non-null  int64
 5   AMT_INCOME_TOTAL     438557 non-null  float64
 6   NAME_INCOME_TYPE     438557 non-null  object
 7   NAME_EDUCATION_TYPE  438557 non-null  object
 8   NAME_FAMILY_STATUS   438557 non-null  object
 9   NAME_HOUSING_TYPE    438557 non-null  object
 10  DAYS_BIRTH           438557 non-null  int64
 11  DAYS_EMPLOYED        438557 non-null  int64
 12  FLAG_MOBIL           438557 non-null  int64
 13  FLAG_WORK_PHONE      438557 non-null  int64
 14  FLAG_PHONE           438557 non-null  int64
 15  FLAG_EMAIL           438557 non-null  int64
 16  OCCUPATION_TYPE      304354 non-null  object
 17  CNT_FAM_MEMBERS      438557 non-null  int64
dtypes: float64(1), int64(9), object(8)
memory usage: 60.2+ MB

In [7]:
df.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [8]:
df.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,4.385570e+05,438557.000000,4.385570e+05,438557.000000,438557.000000,438557.0,438557.000000,438557.000000,438557.000000,438557.000000
mean,6.022176e+06,0.427390,1.875243e+05,-15997.904649,60563.675328,1.0,0.206133,0.287771,0.108207,2.194465
std,5.716370e+05,0.724882,1.100869e+05,4185.030007,138767.799647,0.0,0.404527,0.452724,0.310642,0.897207
min,5.008804e+06,0.000000,2.610000e+04,-25201.000000,-17531.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.609375e+06,0.000000,1.215000e+05,-19483.000000,-3103.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,6.047745e+06,0.000000,1.607805e+05,-15630.000000,-1467.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,6.456971e+06,1.000000,2.250000e+05,-12514.000000,-371.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,7.999952e+06,19.000000,6.750000e+06,-7489.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["AGE"] = (-df["DAYS_BIRTH"] / 365).astype(int)
df[["DAYS_BIRTH", "AGE"]].head(10)

   DAYS_BIRTH  AGE
0      -12005   32
1      -12005   32
2      -21474   58
3      -19110   52
4      -19110   52
5      -19110   52
6      -19110   52
7      -22464   61
8      -22464   61
9      -22464   61

In [11]:
df['YEARS_EMPLOYED'] = np.where(
    df['DAYS_EMPLOYED'] == 365243,
    0,
    df['DAYS_EMPLOYED'].abs() / 365).astype(int)

In [12]:
df['EMPLOYMENT_STATUS'] = np.where(
    df['YEARS_EMPLOYED'] == 0,
    'unemployed',
    'employed'
)

In [13]:
df['YEARS_EMPLOYED'].isna().sum()

np.int64(0)

In [14]:
df[['DAYS_EMPLOYED', 'EMPLOYMENT_STATUS', 'YEARS_EMPLOYED']].head(30)

    DAYS_EMPLOYED EMPLOYMENT_STATUS  YEARS_EMPLOYED
0           -4542          employed              12
1           -4542          employed              12
2           -1134          employed               3
3           -3051          employed               8
4           -3051          employed               8
5           -3051          employed               8
6           -3051          employed               8
7          365243        unemployed               0
8          365243        unemployed               0
9          365243        unemployed               0
10           -769          employed               2
11           -769          employed               2
12           -769          employed               2
13          -1194          employed               3
14          -1194          employed               3
15          -1194          employed               3
16          -1194          employed               3
17          -1194          employed               3
18          -1194          employed               3
19          -1103          employed               3
20          -1103          employed               3
21          -1469          employed               4
22          -1469          employed               4
23          -1469          employed               4
24          -1620          employed               4
25          -1620          employed               4
26          -1620          employed               4
27          -1163          employed               3
28          -1163          employed               3
29          -2016          employed               5

In [15]:
df['YEARS_EMPLOYED'].isnull().sum()

np.int64(0)

In [16]:
df[["YEARS_EMPLOYED","EMPLOYMENT_STATUS"]].head(10)

   YEARS_EMPLOYED EMPLOYMENT_STATUS
0              12          employed
1              12          employed
2               3          employed
3               8          employed
4               8          employed
5               8          employed
6               8          employed
7               0        unemployed
8               0        unemployed
9               0        unemployed

In [17]:
df[['AGE', 'YEARS_EMPLOYED', 'EMPLOYMENT_STATUS']].describe()

                 AGE  YEARS_EMPLOYED
count  438557.000000   438557.000000
mean       43.326489        5.536081
std        11.467500        6.496641
min        20.000000        0.000000
25%        34.000000        1.000000
50%        42.000000        4.000000
75%        53.000000        8.000000
max        69.000000       48.000000

In [18]:
df['EMPLOYMENT_STATUS'].value_counts()

EMPLOYMENT_STATUS
employed      329600
unemployed    108957
Name: count, dtype: int64

In [19]:
df['OCCUPATION_TYPE'] = df['OCCUPATION_TYPE'].fillna('Unknown')

In [20]:
df['OCCUPATION_TYPE'].value_counts(dropna=False)

OCCUPATION_TYPE
Unknown                  134203
Laborers                  78240
Core staff                43007
Sales staff               41098
Managers                  35487
Drivers                   26090
High skill tech staff     17289
Accountants               15985
Medicine staff            13520
Cooking staff              8076
Security staff             7993
Cleaning staff             5845
Private service staff      3456
Low-skill Laborers         2140
Secretaries                2044
Waiters/barmen staff       1665
Realty agents              1041
HR staff                    774
IT staff                    604
Name: count, dtype: int64

In [21]:
df['NAME_INCOME_TYPE'].value_counts()

NAME_INCOME_TYPE
Working                 226104
Commercial associate    100757
Pensioner                75493
State servant            36186
Student                     17
Name: count, dtype: int64

In [22]:
df['NAME_EDUCATION_TYPE'].value_counts()

NAME_EDUCATION_TYPE
Secondary / secondary special    301821
Higher education                 117522
Incomplete higher                 14851
Lower secondary                    4051
Academic degree                     312
Name: count, dtype: int64

In [23]:
df['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 299828
Single / not married     55271
Civil marriage           36532
Separated                27251
Widow                    19675
Name: count, dtype: int64

In [24]:
df['NAME_HOUSING_TYPE'].value_counts()

NAME_HOUSING_TYPE
House / apartment      393831
With parents            19077
Municipal apartment     14214
Rented apartment         5974
Office apartment         3922
Co-op apartment          1539
Name: count, dtype: int64

In [25]:
df[['FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL']].apply(
    lambda x: x.value_counts()
)

   FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL
0         NaN           348156      312353      391102
1    438557.0            90401      126204       47455

In [26]:
df[['NAME_HOUSING_TYPE','CNT_FAM_MEMBERS']].value_counts()

NAME_HOUSING_TYPE    CNT_FAM_MEMBERS
House / apartment    2                  213979
                     1                   73250
                     3                   67887
                     4                   33503
With parents         2                    7523
Municipal apartment  2                    7297
With parents         1                    5387
House / apartment    5                    4639
With parents         3                    4293
Municipal apartment  1                    3435
Rented apartment     2                    2620
Municipal apartment  3                    2367
Office apartment     2                    1867
With parents         4                    1736
Rented apartment     1                    1396
                     3                    1312
Office apartment     3                     949
Municipal apartment  4                     935
Office apartment     1                     631
Rented apartment     4                     609
Co-op apartment      2                     605
House / apartment    6                     435
Office apartment     4                     394
Co-op apartment      1                     393
                     3                     320
                     4                     179
Municipal apartment  5                     163
With parents         5                     136
House / apartment    7                     112
Office apartment     5                      74
Rented apartment     5                      37
Co-op apartment      5                      32
Municipal apartment  6                      15
Co-op apartment      7                      10
House / apartment    9                       9
Office apartment     6                       7
House / apartment    11                      5
                     8                       4
                     14                      4
                     15                      3
Municipal apartment  7                       2
With parents         6                       2
House / apartment    20                      1
Name: count, dtype: int64

In [27]:
df['CNT_CHILDREN'].value_counts()

CNT_CHILDREN
0     304071
1      88527
2      39884
3       5430
4        486
5        133
7          9
9          5
12         4
6          4
14         3
19         1
Name: count, dtype: int64

In [28]:
df.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'AGE',
       'YEARS_EMPLOYED', 'EMPLOYMENT_STATUS'],
      dtype='object')


### credit_record

In [29]:
df_credit = pd.read_csv("C:/Users/Neeresh/OneDrive/Documents/kagglehub/datasets/rikdifos/credit-card-approval-prediction/versions/3/credit_record.csv")
df_credit.head(5)

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

In [30]:
df_credit.shape

(1048575, 3)

In [31]:
df_credit.columns

Index(['ID', 'MONTHS_BALANCE', 'STATUS'], dtype='object')

In [32]:
df_credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   ID              1048575 non-null  int64
 1   MONTHS_BALANCE  1048575 non-null  int64
 2   STATUS          1048575 non-null  object
dtypes: int64(2), object(1)
memory usage: 24.0+ MB

In [33]:
df_credit.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [34]:
df_credit.describe()

                 ID  MONTHS_BALANCE
count  1.048575e+06    1.048575e+06
mean   5.068286e+06   -1.913700e+01
std    4.615058e+04    1.402350e+01
min    5.001711e+06   -6.000000e+01
25%    5.023644e+06   -2.900000e+01
50%    5.062104e+06   -1.700000e+01
75%    5.113856e+06   -7.000000e+00
max    5.150487e+06    0.000000e+00

In [35]:
df_credit.duplicated().sum()

np.int64(0)

In [36]:
# sTATUS		Meaning
# C	        Paid/closed normally
# 0	        1–29 days past due
# X	        No loan/credit activity for that month
# 1	        30–59 days past due	        
# 2	        60–89 days past due
# 3	        90–119 days past due
# 4	        90–119 days past due / severe delinquency
# 5           120+ days past due / serious delinquency
df_credit['STATUS'].value_counts()

STATUS
C    442031
0    383120
X    209230
1     11090
5      1693
2       868
3       320
4       223
Name: count, dtype: int64

In [37]:
df_credit['ID'].nunique()

45985

In [38]:
df_credit['RISK'] = df_credit['STATUS'].isin(['1', '2', '3', '4', '5'])

credit_risk = (
    df_credit.groupby('ID')['RISK']
    .max()
    .astype(int)
    .reset_index()
)

credit_risk.rename(columns={'RISK': 'CREDIT_RISK'}, inplace=True)

credit_risk.head()

        ID  CREDIT_RISK
0  5001711            0
1  5001712            0
2  5001713            0
3  5001714            0
4  5001715            0

In [39]:

credit_risk['CREDIT_RISK'].value_counts()

CREDIT_RISK
0    40635
1     5350
Name: count, dtype: int64

In [40]:
credit_risk

            ID  CREDIT_RISK
0      5001711            0
1      5001712            0
2      5001713            0
3      5001714            0
4      5001715            0
...        ...          ...
45980  5150482            0
45981  5150483            0
45982  5150484            0
45983  5150485            0
45984  5150487            0

[45985 rows x 2 columns]

In [41]:
df_final = df.merge(
    credit_risk,
    on='ID',
    how='inner'
)

In [42]:
df_final

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,...,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE,YEARS_EMPLOYED,EMPLOYMENT_STATUS,CREDIT_RISK
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,...,1,1,0,0,Unknown,2,32,12,employed,1
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,...,1,1,0,0,Unknown,2,32,12,employed,1
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,...,1,0,0,0,Security staff,2,58,3,employed,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,...,1,0,1,1,Sales staff,1,52,8,employed,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,...,1,0,1,1,Sales staff,1,52,8,employed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36452,5149828,M,Y,Y,0,315000.0,Working,Secondary / secondary special,Married,House / apartment,...,1,0,0,0,Managers,2,47,6,employed,1
36453,5149834,F,N,Y,0,157500.0,Commercial associate,Higher education,Married,House / apartment,...,1,0,1,1,Medicine staff,2,33,3,employed,1
36454,5149838,F,N,Y,0,157500.0,Pensioner,Higher education,Married,House / apartment,...,1,0,1,1,Medicine staff,2,33,3,employed,1
36455,5150049,F,N,Y,0,283500.0,Working,Secondary / secondary special,Married,House / apartment,...,1,0,0,0,Sales staff,2,49,1,employed,1
36456,5150337,M,N,Y,0,112500.0,Working,Secondary / secondary special,Single / not married,Rented apartment,...,1,0,0,0,Laborers,1,25,3,employed,1

In [43]:
df_final['ID'].nunique()

36457

In [44]:
df_final['ID'].duplicated().sum()

np.int64(0)

In [45]:
df_final.drop(
    columns=[
        'ID',
        'DAYS_BIRTH',
        'DAYS_EMPLOYED',
        'FLAG_MOBIL'
    ],
    inplace=True
)

In [46]:
df_final.shape

(36457, 18)

In [47]:
df_final.columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_WORK_PHONE',
       'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'AGE',
       'YEARS_EMPLOYED', 'EMPLOYMENT_STATUS', 'CREDIT_RISK'],
      dtype='object')

In [48]:
df_final.select_dtypes(include='object').columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE', 'EMPLOYMENT_STATUS'],
      dtype='object')

In [49]:
df_final.select_dtypes(include='number').columns

Index(['CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'AGE', 'YEARS_EMPLOYED',
       'CREDIT_RISK'],
      dtype='object')

In [50]:
for col in df_final.select_dtypes(include='object').columns:
    print(col, df_final[col].unique())

CODE_GENDER ['M' 'F']
FLAG_OWN_CAR ['Y' 'N']
FLAG_OWN_REALTY ['Y' 'N']
NAME_INCOME_TYPE ['Working' 'Commercial associate' 'Pensioner' 'State servant' 'Student']
NAME_EDUCATION_TYPE ['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
NAME_FAMILY_STATUS ['Civil marriage' 'Married' 'Single / not married' 'Separated' 'Widow']
NAME_HOUSING_TYPE ['Rented apartment' 'House / apartment' 'Municipal apartment'
 'With parents' 'Co-op apartment' 'Office apartment']
OCCUPATION_TYPE ['Unknown' 'Security staff' 'Sales staff' 'Accountants' 'Laborers'
 'Managers' 'Drivers' 'Core staff' 'High skill tech staff'
 'Cleaning staff' 'Private service staff' 'Cooking staff'
 'Low-skill Laborers' 'Medicine staff' 'Secretaries'
 'Waiters/barmen staff' 'HR staff' 'Realty agents' 'IT staff']
EMPLOYMENT_STATUS ['employed' 'unemployed']

In [51]:
X = df_final.drop('CREDIT_RISK', axis=1)
y = df_final['CREDIT_RISK']

In [52]:
X.shape

(36457, 17)

In [53]:

y.shape

(36457,)

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [55]:
X_train.shape

(29165, 17)

In [56]:
X_test.shape

(7292, 17)

In [57]:
y_train.shape

(29165,)

In [58]:
y_test.shape

(7292,)

In [59]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Categorical features
categorical_cols = [
    'CODE_GENDER',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'NAME_INCOME_TYPE',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'OCCUPATION_TYPE',
    'EMPLOYMENT_STATUS'
]

# Numerical features
numerical_cols = [
    'CNT_CHILDREN',
    'AMT_INCOME_TOTAL',
    'FLAG_WORK_PHONE',
    'FLAG_PHONE',
    'FLAG_EMAIL',
    'CNT_FAM_MEMBERS',
    'AGE',
    'YEARS_EMPLOYED'
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(
            handle_unknown='ignore',
            sparse_output=False
        ), categorical_cols)
    ]
)

print("Preprocessor created successfully!")

Preprocessor created successfully!

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

logistic_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(
        max_iter=1000,
        class_weight='balanced'
    ))
])

logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'FLAG_WORK_PHONE',
                                                   'FLAG_PHONE', 'FLAG_EMAIL',
                                                   'CNT_FAM_MEMBERS', 'AGE',
                                                   'YEARS_EMPLOYED']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['CODE_GENDER',
                                                   'FLAG_OWN_CAR',
                                                   'FLAG_OWN_REALTY',
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'EMPLOYMENT_STATUS'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [61]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_lr = logistic_pipeline.predict(X_test)

print(classification_report(
    y_test,
    y_pred_lr,
    target_names=['No Risk', 'Risk']
))

print(confusion_matrix(y_test, y_pred_lr))

              precision    recall  f1-score   support

     No Risk       0.90      0.59      0.71      6434
        Risk       0.14      0.49      0.21       858

    accuracy                           0.57      7292
   macro avg       0.52      0.54      0.46      7292
weighted avg       0.81      0.57      0.65      7292

[[3770 2664]
 [ 441  417]]

In [62]:
from sklearn.neighbors import KNeighborsClassifier

knn_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', KNeighborsClassifier(
        n_neighbors=5
    ))
])

knn_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'FLAG_WORK_PHONE',
                                                   'FLAG_PHONE', 'FLAG_EMAIL',
                                                   'CNT_FAM_MEMBERS', 'AGE',
                                                   'YEARS_EMPLOYED']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['CODE_GENDER',
                                                   'FLAG_OWN_CAR',
                                                   'FLAG_OWN_REALTY',
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'EMPLOYMENT_STATUS'])])),
                ('model', KNeighborsClassifier())])

In [63]:

y_pred_knn= knn_pipeline.predict(X_test)

print(classification_report(
    y_test,
    y_pred_knn,
    target_names=['No Risk', 'Risk']
))

print(confusion_matrix(y_test, y_pred_knn))

              precision    recall  f1-score   support

     No Risk       0.90      0.96      0.93      6434
        Risk       0.46      0.23      0.31       858

    accuracy                           0.88      7292
   macro avg       0.68      0.60      0.62      7292
weighted avg       0.85      0.88      0.86      7292

[[6206  228]
 [ 662  196]]

In [64]:
from sklearn.tree import DecisionTreeClassifier

dt_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', DecisionTreeClassifier(
        random_state=42,
        class_weight='balanced'
    ))
])

dt_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'FLAG_WORK_PHONE',
                                                   'FLAG_PHONE', 'FLAG_EMAIL',
                                                   'CNT_FAM_MEMBERS', 'AGE',
                                                   'YEARS_EMPLOYED']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['CODE_GENDER',
                                                   'FLAG_OWN_CAR',
                                                   'FLAG_OWN_REALTY',
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'EMPLOYMENT_STATUS'])])),
                ('model',
                 DecisionTreeClassifier(class_weight='balanced',
                                        random_state=42))])

In [65]:
y_pred_dt = dt_pipeline.predict(X_test)

print(classification_report(
    y_test,
    y_pred_dt,
    target_names=['No Risk', 'Risk'],
    zero_division=0
))

print(confusion_matrix(y_test, y_pred_dt))

              precision    recall  f1-score   support

     No Risk       0.94      0.80      0.87      6434
        Risk       0.30      0.65      0.41       858

    accuracy                           0.78      7292
   macro avg       0.62      0.73      0.64      7292
weighted avg       0.87      0.78      0.81      7292

[[5155 1279]
 [ 301  557]]

In [66]:
from sklearn.ensemble import RandomForestClassifier

rf_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
    ))
])

rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'FLAG_WORK_PHONE',
                                                   'FLAG_PHONE', 'FLAG_EMAIL',
                                                   'CNT_FAM_MEMBERS', 'AGE',
                                                   'YEARS_EMPLOYED']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['CODE_GENDER',
                                                   'FLAG_OWN_CAR',
                                                   'FLAG_OWN_REALTY',
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'EMPLOYMENT_STATUS'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, n_jobs=-1,
                                        random_state=42))])

In [67]:
y_pred_rf = rf_pipeline.predict(X_test)

print(classification_report(
    y_test,
    y_pred_rf,
    target_names=['No Risk', 'Risk'],
    zero_division=0
))

print(confusion_matrix(y_test, y_pred_rf))

              precision    recall  f1-score   support

     No Risk       0.94      0.82      0.88      6434
        Risk       0.32      0.63      0.42       858

    accuracy                           0.80      7292
   macro avg       0.63      0.72      0.65      7292
weighted avg       0.87      0.80      0.83      7292

[[5300 1134]
 [ 321  537]]

In [68]:
from sklearn.svm import SVC

svm_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', SVC(
        kernel='linear',
        class_weight='balanced',
        random_state=42
    ))
])

svm_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'FLAG_WORK_PHONE',
                                                   'FLAG_PHONE', 'FLAG_EMAIL',
                                                   'CNT_FAM_MEMBERS', 'AGE',
                                                   'YEARS_EMPLOYED']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['CODE_GENDER',
                                                   'FLAG_OWN_CAR',
                                                   'FLAG_OWN_REALTY',
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'EMPLOYMENT_STATUS'])])),
                ('model',
                 SVC(class_weight='balanced', kernel='linear',
                     random_state=42))])

In [69]:
y_pred_svm = svm_pipeline.predict(X_test)

print(classification_report(
    y_test,
    y_pred_svm,
    target_names=['No Risk', 'Risk'],
    zero_division=0
))

print(confusion_matrix(y_test, y_pred_svm))

              precision    recall  f1-score   support

     No Risk       0.89      0.64      0.75      6434
        Risk       0.13      0.41      0.20       858

    accuracy                           0.61      7292
   macro avg       0.51      0.53      0.47      7292
weighted avg       0.80      0.61      0.68      7292

[[4122 2312]
 [ 505  353]]

In [70]:
model_predictions = {
    "Logistic Regression": y_pred_lr,
    "KNN": y_pred_knn,
    "Decision Tree": y_pred_dt,
    "Random Forest": y_pred_rf,
    "SVM": y_pred_svm
}

In [71]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

results = []

for name, predictions in model_predictions.items():

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, predictions),
        "Precision": precision_score(
            y_test, predictions, zero_division=0
        ),
        "Recall": recall_score(
            y_test, predictions, zero_division=0
        ),
        "F1 Score": f1_score(
            y_test, predictions, zero_division=0
        )
    })

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.574191   0.135346  0.486014  0.211729
1                  KNN  0.877948   0.462264  0.228438  0.305772
2        Decision Tree  0.783324   0.303377  0.649184  0.413512
3        Random Forest  0.800466   0.321364  0.625874  0.424674
4                  SVM  0.613686   0.132458  0.411422  0.200397

In [72]:
model_pipelines = {
    "Logistic Regression": logistic_pipeline,
    "KNN": knn_pipeline,
    "Decision Tree": dt_pipeline,
    "Random Forest": rf_pipeline,
    "SVM": svm_pipeline
}

In [73]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

for name, pipeline in model_pipelines.items():

    scores = cross_val_score(
        pipeline,
        X_train,
        y_train,
        scoring='f1',
        cv=cv,
        n_jobs=-1
    )

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    for i, score in enumerate(scores, start=1):
        print(f"Fold {i}: {score:.4f}")

==================================================
Logistic Regression
==================================================
Fold 1: 0.1938
Fold 2: 0.2210
Fold 3: 0.2122
Fold 4: 0.2054
Fold 5: 0.2071

==================================================
KNN
==================================================
Fold 1: 0.2422
Fold 2: 0.2663
Fold 3: 0.2436
Fold 4: 0.2195
Fold 5: 0.2474

==================================================
Decision Tree
==================================================
Fold 1: 0.3905
Fold 2: 0.3747
Fold 3: 0.3987
Fold 4: 0.3878
Fold 5: 0.3915

==================================================
Random Forest
==================================================
Fold 1: 0.4055
Fold 2: 0.3845
Fold 3: 0.4069
Fold 4: 0.3969
Fold 5: 0.4010

==================================================
SVM
==================================================
Fold 1: 0.1899
Fold 2: 0.2087
Fold 3: 0.2122
Fold 4: 0.1962
Fold 5: 0.1905